name: 代码质量检查

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装 linter
      run: |
        pip install --break-system-packages black flake8 isort

    - name: 检查代码格式
      run: |
        black --check .
        isort --check-only .

    - name: 代码风格检查
      run: |
        flake8 .
