name: 测试工作流

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install --break-system-packages pytest pytest-cov
        pip install --break-system-packages wechaty lxml

    - name: 运行测试
      run: |
        python test_zhipu.py

    - name: 生成覆盖率报告
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html

    - name: 上传覆盖率报告
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
